DECLARE
 PTESTREPOS PLS_INTEGER;
 tCount NUMBER;
BEGIN
	IF PTESTREPOS = 1 THEN
		Select count(1) into tCount where status = 'X';
		DBMS_OUTPUT.PUT_LINE("REPOSITORY CREATED SUCCESSFULLY");
	ELSE
		DBMS_OUTPUT.PUT_LINE("REPOSITORY YET TO BE CREATED");
	END IF;

	DBMS_OUTPUT.PUT_LINE("AUNONYMOUS BLOCK COMPLETED SUCCESSFULLY");	
END;