DECLARE
 PTESTREPOS PLS_INTEGER;
BEGIN
	IF PTESTREPOS = 1 THEN
		DBMS_OUTPUT.PUT_LINE("REPOSITORY CREATED SUCCESSFULLY");
	ELSE
		DBMS_OUTPUT.PUT_LINE("REPOSITORY YET TO BE CREATED");
	END IF;

	DBMS_OUTPUT.PUT_LINE("AUNONYMOUS BLOCK COMPLETED SUCCESSFULLY");	
END;